import { Box } from "@mui/material"
import { NavBar } from "./components/nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Box
          sx={{
              mx: 2
          }}
        >
          <NavBar />
          {children}
        </Box>
      </body>
    </html>
    
)
}
